#if !canImport(ObjectiveC)
import XCTest

extension ParserTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ParserTests = [
        ("testCharacterParserFails", testCharacterParserFails),
        ("testCharacterParserSucceeds", testCharacterParserSucceeds),
        ("testDoubleParserFails", testDoubleParserFails),
        ("testDoubleParserFailsWithoutConsumingInput", testDoubleParserFailsWithoutConsumingInput),
        ("testDoubleParserSucceeds", testDoubleParserSucceeds),
        ("testNoneOfParserFails", testNoneOfParserFails),
        ("testNoneOfParserSucceeds", testNoneOfParserSucceeds),
        ("testOneOfParserFails", testOneOfParserFails),
        ("testOneOfParserSucceeds", testOneOfParserSucceeds),
        ("testOneOfParsingManySucceeds", testOneOfParsingManySucceeds),
        ("testParserBetween", testParserBetween),
        ("testParserChoice", testParserChoice),
        ("testParserOption", testParserOption),
        ("testParserRepeatedFailsWhenExpected", testParserRepeatedFailsWhenExpected),
        ("testParserRepeatedPassesWhenExpected", testParserRepeatedPassesWhenExpected),
        ("testStringParserFails", testStringParserFails),
        ("testStringParserSucceeds", testStringParserSucceeds),
        ("testSymbolParserFails", testSymbolParserFails),
        ("testSymbolParserSucceeds", testSymbolParserSucceeds),
        ("testWhitespaceParserFails", testWhitespaceParserFails),
        ("testWhitespaceParserSucceeds", testWhitespaceParserSucceeds),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ParserTests.__allTests__ParserTests),
    ]
}
#endif
